/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MediaRouteImport } from './routes/media'
import { Route as CryptoPosRouteImport } from './routes/crypto-pos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoPosRoute = CryptoPosRouteImport.update({
  id: '/crypto-pos',
  path: '/crypto-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/contact': typeof ContactRoute
  '/crypto-pos': typeof CryptoPosRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/contact': typeof ContactRoute
  '/crypto-pos': typeof CryptoPosRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/contact': typeof ContactRoute
  '/crypto-pos': typeof CryptoPosRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competition'
    | '/contact'
    | '/crypto-pos'
    | '/media'
    | '/products'
    | '/services'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competition'
    | '/contact'
    | '/crypto-pos'
    | '/media'
    | '/products'
    | '/services'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/competition'
    | '/contact'
    | '/crypto-pos'
    | '/media'
    | '/products'
    | '/services'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionRoute: typeof CompetitionRoute
  ContactRoute: typeof ContactRoute
  CryptoPosRoute: typeof CryptoPosRoute
  MediaRoute: typeof MediaRoute
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-pos': {
      id: '/crypto-pos'
      path: '/crypto-pos'
      fullPath: '/crypto-pos'
      preLoaderRoute: typeof CryptoPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionRoute: CompetitionRoute,
  ContactRoute: ContactRoute,
  CryptoPosRoute: CryptoPosRoute,
  MediaRoute: MediaRoute,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
